services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        REPO_URL: ${REPO_URL}
    container_name: nestjs_app
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: unless-stopped