services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        REPO_URL: ${REPO_URL}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      docker_containers_lan:
        ipv4_address: 172.18.0.30 # Baseado na sub-rede ja configurada no host
networks:
  docker_containers_lan:
    external: true