services:
  crm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "80:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
